default: &default
    mirror: http://www.vps.fmvz.usp.br/CRAN/src/contrib/
    max_downloaded_packages: 5
    local_mirror: public/mirror/

development:
    <<: *default

test:
    <<: *default
    mirror: http://mirr/

production:
    mirror: http://cran.r-project.org/src/contrib/
    max_downloaded_packages: 0 # all packages
